<?php

return [
    [
        'name' => 'BATMAN #10',
        'description' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, illum? Nulla aspernatur libero ex ullam possimus sapiente natus nesciunt voluptatem?',
        'cover' => 'BM.jpg',
        'price' => 0.99,
        'available' => true,
        'designer' => 'Pinco Pallino',
        'author' => 'Ayeye',
        'serie' => 'BATMAN 2021',
        'volume' => 4,
        'size' => '6 5/8 X 10 3/16',
        'page_count' => 10,
        'rating' => 'Teen',
    ],
    [
        'name' => 'CRIME SYNDICATE #1',
        'description' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, illum? Nulla aspernatur libero ex ullam possimus sapiente natus nesciunt voluptatem?',
        'cover' => 'CRIMESYM.jpg',
        'price' => 0.99,
        'available' => true,
        'designer' => 'Pinco Pallino',
        'author' => 'Ayeye',
        'serie' => 'CRIME SYNDICATE 2021',
        'volume' => 6,
        'size' => '6 5/8 X 10 3/16',
        'page_count' => 10,
        'rating' => 'Teen',
    ],
    [
        'name' => 'INFINITE FRONTIER #0',
        'description' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, illum? Nulla aspernatur libero ex ullam possimus sapiente natus nesciunt voluptatem?',
        'cover' => 'INFRONTIER.jpg',
        'price' => 0.99,
        'available' => true,
        'designer' => 'Pinco Pallino',
        'author' => 'Ayeye',
        'serie' => 'INFINITE FRONTIER 2021',
        'volume' => 0,
        'size' => '6 5/8 X 10 3/16',
        'page_count' => 10,
        'rating' => 'Teen',
    ],
    [
        'name' => 'MAN-BAT #2',
        'description' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, illum? Nulla aspernatur libero ex ullam possimus sapiente natus nesciunt voluptatem?',
        'cover' => 'MANBAT.jpg',
        'price' => 0.99,
        'available' => true,
        'designer' => 'Pinco Pallino',
        'author' => 'Ayeye',
        'serie' => 'MAN-BAT 2021',
        'volume' => 2,
        'size' => '6 5/8 X 10 3/16',
        'page_count' => 10,
        'rating' => 'Teen',
    ],
    [
        'name' => 'SENSATIONAL WONDER WOMAN #9',
        'description' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, illum? Nulla aspernatur libero ex ullam possimus sapiente natus nesciunt voluptatem?',
        'cover' => 'SWW.jpg',
        'price' => 0.99,
        'available' => true,
        'designer' => 'Pinco Pallino',
        'author' => 'Ayeye',
        'serie' => 'SENSATIONAL WONDER WOMAN 2021',
        'volume' => 9,
        'size' => '6 5/8 X 10 3/16',
        'page_count' => 10,
        'rating' => 'Teen',
    ],
    
    
];